spring:
    profiles:
      active: dev
    datasource:
      url: jdbc:postgresql://localhost:5432/root
      username: root
      password: root12345
    jpa:
      properties:
        hibernate:
          default_schema: creditx_dev