CREATE TABLE CREDIT_RISK
(

  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  credit_limit DOUBLE PRECISION NOT NULL,
  risk_type VARCHAR(1) NOT NULL,
  interest_percentage DOUBLE PRECISION NOT NULL

);